name=QMan
version=1.0.7-beta
author=Ilia Vinokurov
maintainer=Ilia Vinokurov <ilvin@mail.ru>
sentence=Ultra-lightweight cooperative DSL scheduler for Arduino.
paragraph=A high-performance task manager with static task counting, priority queue, and watchdog protection. Perfect for AVR/LGT8F.
category=Timing
url=https://github.com/IlVin/QMan
architectures=*
includes=QMan.h
